### ISSUE TITLE
Closure bug

### ISSUE THREAD

**Issue by edemaine** [edemaine/coffeescript-for-python#28]
Python version of for/do example doesn't work. Need optional arguments.

**Comment by adqm** [comment]
There are a couple of different ways to rewrite that Python example to exhibit the behavior you want to show.  One would be using default arguments like you mention:

```
def delay(bits):
  out = []
  for bit in bits:
    def g(bit=bit):
      return bit
    out.append(g)
  return out
```

Another would be to explicitly use a closure (if you wanted not to worry about the details of Python's default argument evaluation).  I imagine this is closer to what coffeescript compiles `do` down to:

```
def delay(bits):
  out = []
  for bit in bits:
    def _makeg(bit):
      def g(): 
        return bit
      return g
    out.append(_makeg(bit))
  return out
```

But I wouldn't write things that way.  A far more concise implementation is:

```
def delay(bits):
  return [(lambda n: lambda: n)(bit) for bit in bits]
```

**Comment by edemaine** [comment]
@adqm Thanks! I've gone with the default solution, because it's how I would have written it in my Python days.  Agreed, your other code is what CoffeeScript compiles the `do` to; here's a snippet:
```js
results.push((function(bit) { // force locally scoped bit
      return function() {
        return bit;
      };
    })(bit));
```
