### ISSUE TITLE
Splats (...) placement

### ISSUE THREAD

**Issue by andy-kwei** [edemaine/coffeescript-for-python#47]
The splats operator (...) should be placed after the variable name, instead of before (although for Javascript, it is the reverse). See https://coffeescript.org/#splats.

**Comment by edemaine** [comment]
@andy-kwei I'm pretty sure CoffeeScript (v2) supports splats before or after the variable name. I agree that this should probably be mentioned in this document.

**Comment by andy-kwei** [comment]
You're right - I was running on an old version.
